version: 2

models:
  - name: stg_online_retail
    description: |
      This staging model contains cleaned and preprocessed retail data. 
      Main preparation steps include:
        - Removing null or duplicate records
        - Standardizing product descriptions
        - Converting currencies into a common format
    columns:
      - name: InvoiceNo
        description: "Unique invoice identifier"
        tests:
          - not_null
          - unique
      - name: CustomerID
        description: "Unique customer identifier"
        tests:
          - not_null
      - name: Country
        description: "Customer's country of origin"
        tests:
          - accepted_values:
              values: ['United Kingdom', 'France', 'Germany', 'EIRE', 'Spain']

  - name: dl_input
    description: |
      This model prepares user-item interaction pairs for the Deep Learning recommendation system. 
      Steps include:
        - Selecting top-N products based on frequency
        - Mapping users and items to numeric IDs
        - Normalizing the format for model input
    columns:
      - name: user_id
        description: "User identifier mapped to numeric ID"
        tests:
          - not_null
      - name: item_id
        description: "Item identifier mapped to numeric ID"
        tests:
          - not_null

  - name: fpgrowth_input
    description: |
      This model generates transaction-style item lists for the FP-Growth algorithm. 
      Steps include:
        - Grouping products by invoice
        - Creating item lists that represent products bought together
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        tests:
          - not_null
          - unique
      - name: item_list
        description: "List of items purchased in the transaction"
